language: rust
services: docker
sudo: required

matrix:
  include:
    - rust: 1.31.0
      script: cargo test --verbose --all --exclude aead --exclude signature --exclude universal-hash --release
    - rust: 1.36.0
      script: cargo test --verbose --package aead --package signature --package universal-hash --release
    - rust: stable
      script: cargo test --verbose --all --release
    - rust: nightly
      script: cargo test --verbose --all --release
    # tests if crates can be built with std feature
    - rust: 1.31.0
      script: ./build_std.sh

    - env: TARGET=i686-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: stable
    # tests if crates truly can be built without std
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      script: xargo build --all --exclude aead --exclude signature --verbose --target $TARGET
      install:
        - cargo install xargo || true
        - rustup target install armv7-unknown-linux-gnueabihf
        - rustup component add rust-src

install:
  - cargo install cross || true

script:
  - cross test --verbose --all --exclude signature_derive --release --target $TARGET

cache: cargo
