[files]
extend-exclude = [
    ".git/",
    "signature/tests/derive.rs"
]

[default]
extend-ignore-re = [
    # Patterns which appear to be 36 or more characters of Base64/Base64url
    '\b[0-9A-Za-z+/]{36,}\b',
    '\b[0-9A-Za-z_-]{36,}\b',
]

[default.extend-words]
consts = "consts"
# Authenticated Key Exchange
"AKE" = "AKE"
