[workspace]
resolver = "2"
members = [
    "aead",
    "async-signature",
    "cipher",
    "crypto",
    "crypto-common",
    "digest",
#    "elliptic-curve",
    "kem",
    "password-hash",
#    "signature",
    "signature_derive",
    "universal-hash",
]
exclude = ["elliptic-curve", "signature"]
