[workspace]
resolver = "3"
members = [
    "aead",
    "cipher",
    "crypto",
    "crypto-common",
    "digest",
    "elliptic-curve",
    "kem",
    "password-hash",
    "universal-hash",
    "signature",
]

[patch.crates-io]
digest = { path = "digest" }
signature = { path = "signature" }

crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint", branch = "rand_core/v0.10.0-rc-2" }
ff = { git = "https://github.com/tarcieri/ff", branch = "rand_core/v0.10.0-rc-2" }
group = { git = "https://github.com/tarcieri/group", branch = "rand_core/v0.10.0-rc-2" }
