[package]
name = "elliptic-curve"
version = "0.13.0-pre"
description = """
General purpose Elliptic Curve Cryptography (ECC) support, including types
and traits for representing various elliptic curve forms, scalars, points,
and public/secret keys composed thereof.
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/RustCrypto/traits/tree/master/elliptic-curve"
readme = "README.md"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "elliptic", "weierstrass"]
edition = "2021"
rust-version = "1.61"

[dependencies]
base16ct = "0.1.1"
crypto-bigint = { version = "=0.5.0-pre.2", default-features = false, features = ["rand_core", "generic-array", "zeroize"] }
generic-array = { version = "0.14", default-features = false }
rand_core = { version = "0.6.4", default-features = false }
subtle = { version = "2", default-features = false }
zeroize = { version = "1.5", default-features = false }

# optional dependencies
base64ct = { version = "1", optional = true, default-features = false }
digest = { version = "0.10", optional = true }
ff = { version = "0.13", optional = true, default-features = false }
group = { version = "0.13", optional = true, default-features = false }
hkdf = { version = "0.12", optional = true, default-features = false }
hex-literal = { version = "0.3", optional = true }
pem-rfc7468 = { version = "0.6", optional = true }
pkcs8 = { version = "0.9", optional = true, default-features = false }
sec1 = { version = "0.3", optional = true, features = ["subtle", "zeroize"] }
serdect = { version = "0.1", optional = true, default-features = false, features = ["alloc"] }
serde_json = { version = "1", optional = true, default-features = false, features = ["alloc"] }

[dev-dependencies]
hex-literal = "0.3"
sha2 = "0.10"
sha3 = "0.10"

[features]
default = ["arithmetic"]
alloc = [
    "base16ct/alloc",
    "ff?/alloc",
    "group?/alloc",
    "pkcs8?/alloc",
    "sec1?/alloc",
    "zeroize/alloc"
]
std = [
    "alloc",
    "rand_core/std",
    "sec1?/std"
]

arithmetic = ["group"]
bits = ["arithmetic", "ff/bits"]
dev = ["arithmetic", "hex-literal", "pem", "pkcs8"]
hash2curve = ["arithmetic", "digest"]
ecdh = ["arithmetic", "digest", "hkdf"]
group = ["dep:group", "ff"]
hazmat = []
jwk = ["alloc", "base64ct/alloc", "serde", "serde_json", "zeroize/alloc"]
pkcs8 = ["dep:pkcs8", "sec1"]
pem = ["alloc", "arithmetic", "pem-rfc7468/alloc", "pkcs8", "sec1/pem"]
serde = ["alloc", "sec1/serde", "serdect"]
voprf = ["digest"]

[package.metadata.docs.rs]
features = ["bits", "ecdh", "hash2curve", "jwk", "pem", "std", "voprf"]
rustdoc-args = ["--cfg", "docsrs"]
